---
- name: AWS | VPC | CAGW | Init
  ansible.builtin.debug:
    msg: "Destroy VPC CAGW triggered"
  tags: vpc

  #- name: AWS | VPC | CAGW | Delete
  #  ec2_carrier_gateway:
  #    region: "{{ vpc_region }}"
  #  vpc_id: "{{ vpc_id }}"
  #  state: "absent"
  #with_items: "{{ vpc_info.vpcs }}"
  #tags: vpc
