---
- name: AWS | DNS | RR | Init
  ansible.builtin.debug:
    msg: "Destroy DNS Records for zone: {{ zone.name }}"
  tags: dns
  when: debug|d(false)

- name: AWS | DNS | RR | Delete
  ansible.builtin.include_tasks: aws-dns-record.yaml
  with_items: "{{ okd_cluster_destroy_dns_records }}"
  loop_control:
    loop_var: record
  tags: dns
