---
- name: AWS | DNS | Init
  ansible.builtin.debug:
    msg: "Destroy DNS triggered"
  tags: dns
  when: debug|d(false)

- name: AWS | DNS | Delete records
  ansible.builtin.include_tasks: aws-dns-records.yaml
  with_items: "{{ cloud_dns_zones }}"
  loop_control:
    loop_var: zone
  tags: dns

- name: AWS | DNS | Delete zones
  ansible.builtin.include_tasks: aws-dns-zone.yaml
  when: zone.private_zone | d(false)
  with_items: "{{ cloud_dns_zones }}"
  loop_control:
    loop_var: zone
  tags: dns
