---
- name: AWS | IAM | Init
  ansible.builtin.debug:
    msg: "Destroy IAM triggered"

- name: AWS | IAM | Policies
  ansible.builtin.include_tasks: aws-iam-policies.yaml
  with_items: "{{ iam_roles }}"
  loop_control:
    loop_var: iam_role

- name: AWS | IAM | Roles | Remove
  community.aws.iam_role: 
    state: absent
    name: "{{ item.name }}"
  with_items: "{{ iam_roles }}"
  register: result
  ignore_errors: True
  changed_when:
    - result.rc == 2
