---
- name: AWS | IAM | Policies | Init
  ansible.builtin.debug:
    msg: "Destroy IAM triggered"

# TODO discovery if role exists before try to delete policy
- name: AWS | IAM | Policies | Remove
  community.aws.iam_policy:
    state: absent
    iam_type: role
    iam_name: "{{ iam_role.name }}"
    policy_name: "{{ item.name }}"
  with_items: "{{ iam_role.custom_policies | d([]) }}"
  register: result
  ignore_errors: True
  changed_when:
    - result.rc == 2
