--- # top level global collection vars

collection_work_dir: "{{ workdir | d(lookup('env', 'HOME') + '/.ansible/okd-installer') }}"
collection_tmp_dir:  "{{ tempdir | d(collection_work_dir + '/tmp') }}"
collection_bin_dir:  "{{ bindir | d(collection_work_dir + '/bin') }}"
collection_cluster_dir:  "{{ bindir | d(collection_work_dir + '/clusters') }}"

# Config

config_install_dir: "{{ collection_cluster_dir }}/{{ cluster_name }}"
bin_openshift_install: "{{ collection_bin_dir }}/openshift-install"
bin_oc: "{{ collection_bin_dir }}/openshift-install"

## export CONFIG_PULL_SECRET_FILE=${HOME}/.openshift/pull-secret-latest.jso
config_pull_secret_file: "{{ lookup('ansible.builtin.env', 'CONFIG_PULL_SECRET_FILE') }}"
## export CONFIG_SSH_KEY=$(cat ~/.ssh/id_rsa.pub)
config_ssh_key: "{{ lookup('ansible.builtin.env', 'CONFIG_SSH_KEY') }}"
## Use custom CLUSTER_NAME on config metadata.name
config_metadata_name: "{{ cluster_name | d(lookup('ansible.builtin.env', 'CONFIG_CLUSTER_NAME')) }}"
## export CONFIG_BASE_DOMAIN=devcluster.openshift.com
config_base_domain: "'{{ lookup('ansible.builtin.env', 'CONFIG_BASE_DOMAIN') }}'"

config_cluster_region: "{{ lookup('ansible.builtin.env', 'CONFIG_CLUSTER_REGION') }}"

# Provider: is the Cloud Provider. Examples: aws, do, MomPopCloud
## Provider should be supported by Collection okd-installer
config_provider: "{{ provider | d(lookup('ansible.builtin.env', 'CONFIG_PROVIDER', default='aws')) }}"

# Platform: is the OCP Platform Integration. Exmaples: aws, none, azure
## Platform should be one supported by OpenShift, even using 'none'
config_platform: "{{ lookup('ansible.builtin.env', 'CONFIG_PLATFORM', default='none') }}"
config_platform_spec: "{{ lookup('ansible.builtin.env', 'CONFIG_PLATFORM_SPEC', default={'region':config_cluster_region}) }}"

# Network Defaults
okd_net_default_cidr: 10.0.0.0/16
