---

- name: Getting existing nodes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    label_selectors:
      - "node-role.kubernetes.io/worker"
    kubeconfig: "{{ config_install_dir }}/auth/kubeconfig"
  register: all_nodes

- name: Set worker node counter
  ansible.builtin.set_fact:
    cert_nodes_count: "{{ all_nodes.resources|length|int }}"

- name: Set Approval Done
  ansible.builtin.set_fact:
    cert_approval_done: yes
  when: cert_nodes_count|int >= cert_expected_nodes|int

- name: Show Approval state
  ansible.builtin.debug:
    msg:
      - "Total Worker Nodes (joined)=[{{ cert_nodes_count }}]"
      - "Total Worker Nodes (expected)=[{{ cert_expected_nodes }}]"
      - "Total certs sapproved=[{{ cert_approved }}]"
      - "CSR Approver Done=[{{ cert_approval_done }}]"

- name: Start CSR approval
  ansible.builtin.include_tasks: approve.yaml
  when: not(cert_approval_done)
