---

- name: Getting existing nodes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    label_selectors:
      - "node-role.kubernetes.io/worker"
    kubeconfig: "{{ config_install_dir }}/auth/kubeconfig"
  register: all_nodes
  until: "all_nodes is not failed"
  retries: 5
  delay: 5

- name: Set worker node counter
  ansible.builtin.set_fact:
    cert_nodes_count: "{{ all_nodes.resources | length | int }}"

- name: Set Approval Done
  ansible.builtin.set_fact:
    cert_approval_done: yes
  when: cert_nodes_count|int >= cert_expected_nodes|int

- name: Set waiting message
  ansible.builtin.set_fact:
    waiting_msg: "{{ cert_wait_interval_sec }}sec [{{ item_retry }}/{{ end_at }}]"

- name: Show Approval state
  ansible.builtin.debug:
    msg:
      - "CSR Approver Done            =[{{ cert_approval_done }}]"
      - "CSR Approver Interval        ={{ waiting_msg }}"
      - "Total Worker Nodes (joined)  =[{{ cert_nodes_count }}]"
      - "Total Worker Nodes (expected)=[{{ cert_expected_nodes }}]"
      - "Total certificates approved  =[{{ cert_approved }}]"

- name: Start CSR approval
  ansible.builtin.include_tasks: approve.yaml
  when: not(cert_approval_done)
