---

- name: "Waiting [{{ cert_wait_interval_sec }}s] to retrieve CSRs [{{ item_retry }}/{{ end_at }}]"
  ansible.builtin.pause:
    seconds: "{{ cert_wait_interval_sec }}"

- name: "Getting existing Certificate Signing Requests"
  kubernetes.core.k8s_info:
    api_version: certificates.k8s.io/v1
    kind: CertificateSigningRequest
    kubeconfig: "{{ config_install_dir }}/auth/kubeconfig"
  register: all_csr

- name: "Set default pending"
  set_fact:
    csr_pending: []

- name: filter pending CertificateSigningRequest
  set_fact:
    csr_pending: "{{ csr_pending | d([]) + [ item_csr.metadata.name ] }}"
  with_items: "{{ all_csr.resources }}"
  when: "{{ item_csr.status | length <= 0 }}"
  loop_control:
    loop_var: item_csr
  register: pending_csr_out
  until: "csr_pending | length > 0"
  retries: 3
  delay: 10

- name: Show Total Pending
  debug:
    msg: "Total pending: {{ csr_pending|length }}"

- name: approve CertificateSigningRequest
  command: |
    {{ oc_bin }} \
      --kubeconfig {{ config_install_dir }}/auth/kubeconfig \
      adm certificate approve {{ csr_name }}
  vars:
    oc_bin: "{{ ansible_user_dir }}/.ansible/okd-installer/bin/oc"
  with_items: "{{ csr_pending }}"
  loop_control:
    loop_var: csr_name

- name: Update Total Approved
  ansible.builtin.set_fact:
    certs_approved: "{{ certs_approved|int + csr_pending|length }}"

- name: Show Total Approved
  debug:
    msg: "Total approved: {{ certs_approved }}"

# - name: Check for approval
#   debug:
#     msg: "Skipping pause. {{ certs_expected }}"
#   when:
#   - (certs_expected|int != 0) and (certs_approved|int == certs_expected|int)
