---

- name: "Approving Node Certificates"
  ansible.builtin.include_tasks: approve-check.yaml
  with_sequence: start=1 end="{{ end_at }}"
  vars:
    end_at: "{{ cert_max_retries | d(cert_default_max_retries) }}"
  loop_control:
    loop_var: item_retry
  when: not(cert_approval_done)
