---

cloud_load_balancer_provider: do

#> DO LB is limited the HC by LB, not rule, so it can be a problem
#> when specific service goes down. Recommened is to create one LB by
#> rule with proper health check (not cover here)
cloud_loadbalancers:
  - provider: do
    vpc_name: "{{ cluster_state.infra_id }}-vpc"
    spec:
      name: "{{ cluster_state.infra_id }}-ext"
      state: present
      project_name: "{{ cluster_state.infra_id }}"
      region: "{{ cluster_state.region }}"
      redirect_http_to_https: no
      size: "lb-small"
      #algorithm: round_robin
      enable_backend_keepalive: no
      enable_proxy_protocol: no
      wait: true
      tag: "{{ cluster_state.infra_id }}-control-planes"
      forwarding_rules:
        - entry_protocol: tcp
          entry_port: 6443
          target_protocol: tcp
          target_port: 6443
          tls_passthrough: false
        - entry_protocol: tcp
          entry_port: 22623
          target_protocol: tcp
          target_port: 22623
          tls_passthrough: false
        - entry_protocol: tcp
          entry_port: 80
          target_protocol: tcp
          target_port: 80
          tls_passthrough: false
        - entry_protocol: tcp
          entry_port: 443
          target_protocol: tcp
          target_port: 443
          tls_passthrough: false
      health_check:
        check_interval_seconds: 10
        healthy_threshold: 5
        path: "/healthz"
        port: 6443
        protocol: "https"
        response_timeout_seconds: 5
        unhealthy_threshold: 3

    callbacks:
      - service: dns
        domain: "{{ cluster_state.dns.cluster_domain }}"
        records:
        - name: "lb-api"
          type: A
        - name: "api"
          value: "lb-api"
          type: CNAME
        - name: "api-int"
          value: "lb-api"
          type: CNAME

  # ingress LB
  - provider: do
    vpc_name: "{{ cluster_state.infra_id }}-vpc"
    spec:
      name: "{{ cluster_state.infra_id }}-ingress-pub"
      state: present
      project_name: "{{ cluster_state.infra_id }}"
      region: "{{ cluster_state.region }}"
      redirect_http_to_https: no
      size: "lb-small"
      #algorithm: round_robin
      enable_backend_keepalive: no
      enable_proxy_protocol: no
      wait: true
      tag: "{{ cluster_state.infra_id }}-compute-nodes"
      forwarding_rules:
        - entry_protocol: tcp
          entry_port: 80
          target_protocol: tcp
          target_port: 80
          tls_passthrough: false
        - entry_protocol: tcp
          entry_port: 443
          target_protocol: tcp
          target_port: 443
          tls_passthrough: false
      health_check:
        check_interval_seconds: 10
        healthy_threshold: 5
        #path: "/healthz"
        port: 80
        protocol: tcp
        response_timeout_seconds: 5
        unhealthy_threshold: 3

    callbacks:
      - service: dns
        domain: "{{ cluster_state.dns.cluster_domain }}"
        records:
        - name: "lb-ingress"
          type: A
        - name: "*.apps"
          value: "lb-ingress"
          type: CNAME
        - name: "oauth-openshift.app"
          value: "lb-ingress"
          type: CNAME