site_name: "@okd-installer (Ansible Collection)"
#site_url: https://mtulio.net
#site_author: 'Marco Braga'
site_description: >-
  Ansible Collection okd-installer
repo_url: https://github.com/mtulio/ansible-collection-okd-installer
edit_uri: edit/main/docs/
docs_dir: ./docs
site_dir: ./site
dev_addr: 127.0.0.1:8080

theme:
  # https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    - navigation.top
    #- navigation.indexes

    # integrate menus
    #- toc.integrate
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      lang:
      - en
  - diagrams:
      file_extension: ".diagram.py"
      max_workers: 5

markdown_extensions:
  # - toc:
  #     permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  # enable mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home:
      - Welcome: index.md
      - How it works: Getting-started.md
  - Deployment:
    - Installation Guide: Installing.md
    - Configurations: TODO.md
    - Playbooks:
        - Installing Clients: installing/install-openshift-install.md
        - Create Cluster: TODO.md
        - Destroy Cluster: TODO.md
        - Config Create: TODO.md
        - Config Manifest: TODO.md
        - Config Patch Manifests: TODO.md
        - Config Ignitions: TODO.md
        - OS Mirror: TODO.md
        - Stack IAM: TODO.md
        - Stack Network: TODO.md
        - Stack DNS: TODO.md
        - Stack Load Balancer: TODO.md
        - Stack Compute: TODO.md
        - Approve Certificates: TODO.md
    - Integrating Provider: Onboarding.md
  - Guide:
    - Guides: TODO.md
    - AWS:
      - Installing HA Topology with UPI: installing/aws-upi.md
      - Installing HA Topology with UPI and Platform Agnostic: installing/aws-agnostic.md
      - Installing SNO with Ephemeral storage: installing/aws-sno.md
      - Installing HA Topology UPI BYO Network: installing/aws-upi-byo-network.md
    - Digital Ocean: TODO.md
    - Oracle Cloud:
      - Installing HA Topology with UPI and Platform Agnostic: TODO.md
      - Installing HA Topology with UPI and Platform External: TODO.md
      - Installing HA Topology with UPI and Platform External and CSI Driver: TODO.md
  - Examples: TODO.md
  - Development:
    - index.md
    - Creating Diagrams: dev/diagrams.md
    - Releasing: dev/releasing.md
    - Adding Config Provider: dev/adding-config-provider.md
    - Tests: dev/tests.md
