site_name: "@okd-installer (Ansible Collection)"
#site_url: https://mtulio.net
#site_author: 'Marco Braga'
site_description: >-
  Ansible Collection okd-installer
repo_url: https://github.com/mtulio/ansible-collection-okd-installer
edit_uri: edit/main/docs/
docs_dir: ./docs
site_dir: ./site
dev_addr: 127.0.0.1:8080

theme:
  # https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes

    # integrate menus
    #- toc.integrate
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link

    # copy clipboard
    - content.code.copy

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      lang:
      - en
  - diagrams:
      file_extension: ".diagram.py"
      max_workers: 5

markdown_extensions:
  # - toc:
  #     permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  # enable mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # enable modules (include md files)
  - pymdownx.snippets:
      check_paths: true

  # copy clipboard feature (content.code.copy)
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home:
    - index.md
    - How it works: Getting-started.md
  - Guides:
    - guides/index.md
    - AWS:
      - guides/AWS/index.md
      - guides/AWS/installing-quickly-agnostic.md
      - Installing SNO with Ephemeral storage: guides/AWS/aws-sno.md
      - Scripts:
        - guides/AWS/script/installing-quickly-agnostic.md
      - "-> Review In Progress:": TODO.md
      - Installing HA Topology with UPI and Platform Agnostic: guides/AWS/aws-agnostic.md
      - Installing HA Topology with UPI: guides/AWS/aws-upi.md
      - Installing HA Topology UPI BYO Network: guides/AWS/aws-upi-byo-network.md
    - Oracle Cloud Infrastructure:
      - guides/OCI/index.md
      - "Requirements": guides/OCI/init.md
      - Installing a cluster quickly on OCI with platform agnostic (None): guides/OCI/installing-quickly-agnostic.md
      - Installing a cluster quickly on OCI with platform external (External): guides/OCI/installing-quickly-external.md
      - Installing a cluster on OCI with infrastructure customizations: guides/OCI/installing-customization-infra.md
      - Installing a cluster on OCI using platform external (External) with CCM customizations: guides/OCI/installing-customization-external.md
      - Installing a cluster on OCI with Assisted Installer: guides/OCI/installing-assisted-installer.md
      - Setting up the registry storage with OCI Bucket: guides/OCI/setting-registry-storage-bucket.md
      - Lab / Examples distributed/reused vars: guides/OCI/lab-examples-custom-vars.md
      - Testing the installation with Kubernetes/OpenShift conformance test suites: guides/OCI/testing-opct-conformance.md
      - hack/platform external development/building custom components in OKD: guides/OCI/hack/dev-platform-external-custom-release.md
    - Dev Call - Cloud Provider Opportunities for OKD: guides/opportunities.md
  - Deployment:
    - deployment/index.md
    - Installation Guide: deployment/installing.md
    - Configurations: deployment/configuration.md
    - Playbooks:
      - deployment/playbooks/index.md
      - approve_certs: TODO.md
      - config_load: TODO.md
      - create_all: TODO.md
      - create_node: TODO.md
      - create_node_all: TODO.md
      - config_dump: TODO.md
      - config:
        - TODO.md
        - Config Manifest: TODO.md
        - Config Patch Manifests: TODO.md
        - Config Ignitions: TODO.md
      - create_imageregistry: TODO.md
      - destroy_cluster: TODO.md
      - destroy_bootstrap: TODO.md
      - install_clients: TODO.md
      - os_mirror: TODO.md
      - stack_dns: TODO.md
      - stack_loadbalancer: TODO.md
      - stack_iam: TODO.md
      - stack_network: TODO.md
      - ping: TODO.md
      - var_check_required: TODO.md
      - Global Vars:
        - TODO.md
    - Roles:
      - deployment/roles/index.md
      - clients: TODO.md
      - bootstrap: TODO.md
      - config: TODO.md
      - csr_approver: TODO.md
      - destroy: TODO.md
      - cloud_compute: TODO.md
      - cloud_dns: TODO.md
      - cloud_iam: TODO.md
      - cloud_load_balancer: TODO.md
      - cloud_network: TODO.md
    - Integrating Provider: deployment/integrating.md
  #- Examples: TODO.md
  - Development:
    - development/index.md
    - Creating Diagrams: development/diagrams.md
    - Releasing: development/releasing.md
    - Adding Config Provider: development/adding-config-provider.md
    - Tests: development/tests.md
  - About:
    - Why this project?: about-why.md
    - License: LICENSE