# NOTE: before bumping the version of Collections it's important to
# test the entire Collection workflow (create/delete) using both
# virtual and containerized environments.
# The here is to keep the major(x) version of Collections with the same
# of the distributed on the ansible minor version(y).

collections:
- name: community.general
- name: ansible.posix
- name: community.kubernetes
  version: '>=2.0.0,<3.0.0'

# AWS modules
- name: community.aws
  version: '>=5.5.0,<5.6'
- name: amazon.aws
  version: '>=5.5.0,<5.6'
