---
release_arch: x86_64
default_version: 4.11.0
# OCP follows the arch on the name
# https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/
release_version: "{{ version | d(default_version) }}-{{ release_arch }}"

# OKD has only the version
# https://amd64.origin.releases.ci.openshift.org/
#release_version: 4.11.0-0.okd-2022-08-20-022919

# https://amd64.origin.releases.ci.openshift.org/
release_image: "quay.io/openshift-release-dev/ocp-release"
#release_image: "quay.io/openshift/okd"

release_image_version_arch: "{{ release_image }}:{{ release_version }}"

workdir: "{{ lookup('env', 'HOME') }}/.ansible/okd-installer"
client_os: linux
