---

- include: check.yaml
- include: create-assertions.yaml

- name: InstallerConfig | Check if metadata.json exists
  stat:
    path: "{{ config_install_dir }}/metadata.json"
  register: st_out

- name: InstallerConfig | Create the install config
  template:
    src: ocp-install-config.yaml.j2
    dest: "{{ config_install_dir }}/install-config.yaml"
    mode: 0644
  when: not(st_out.stat.exists)

- name: InstallerConfig | Backup the rendered install config
  template:
    src: ocp-install-config.yaml.j2
    dest: "{{ config_install_dir }}/install-config-bkp.yaml"
    mode: 0644
  when: not(st_out.stat.exists)

- name: InstallerConfig | Create manifests
  shell: |
    {{ bin_openshift_install }} create manifests --dir {{ config_install_dir }}
  when: not(st_out.stat.exists)

- name: InstallerConfig | Remove Cluster/Machine API manifests for UPI
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_master-machines-1.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_master-machines-2.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_master-machines-3.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-1.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-2.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-3.yaml"
  when: not(st_out.stat.exists)

- name: InstallerConfig | Create ignition configs
  shell: |
    {{ bin_openshift_install }} create ignition-configs --dir {{ config_install_dir }}
  when: not(st_out.stat.exists)
