FROM quay.io/centos/centos:stream9

WORKDIR /okd-installer

RUN dnf install python3-pip -y \
    && dnf clean all

ADD ./requirements.* .
ADD ./build/*.tar.gz ./mtulio.okd_installer.tar.gz

RUN pip3 install --force-reinstall -r requirements.txt \
    && ansible-galaxy collection install --requirements-file requirements.yml \
    && ansible-galaxy collection install ./mtulio.okd_installer.tar.gz
