---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  connection: local
  gather_facts: false
  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true
