---
- name: Destroy | VPC | AWS
  ansible.builtin.debug:
    msg: "Destroy VPC triggered"
  tags: vpc
  when: debug|d(false)

- name: VPC | AWS | Set VPC Id for Zone name
  ansible.builtin.set_fact:
    vpc_name: "{{ cloud_networks[0].name }}"
    vpc_region: "{{ cloud_networks[0].region }}"
    vpc_cidr: "{{ cloud_networks[0].block }}"
  tags: vpc

- name: VPC | AWS | Get VPC by Name
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc_name }}"
  when: vpc_name is defined
  register: vpc_info
  tags: vpc

- name: VPC | AWS | Set VPC Id for Zone name
  ansible.builtin.set_fact:
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
  when:
    - vpc_name is defined
    - vpc_info.vpcs|length > 0
  tags: vpc

- name: Include Network tasks to delete
  when: (vpc_id is defined) and (vpc_id != '')
  tags: vpc
  block:
    - name: Delete Nat Gateway(s)
      ansible.builtin.include_tasks: aws-vpc-natgw.yaml
      tags: vpc

    - name: Delete Security Group(s)
      ansible.builtin.include_tasks: aws-vpc-sgs.yaml
      tags: vpc

    - name: Delete VPC Endpoint(s)
      ansible.builtin.include_tasks: aws-vpc-endpoint.yaml
      tags: vpc

    - name: Delete Route Table(s)
      ansible.builtin.include_tasks: aws-vpc-rtb.yaml
      tags: vpc

    - name: Delete Subnet(s)
      ansible.builtin.include_tasks: aws-vpc-subnets.yaml
      tags: vpc

    - name: Delete Internet Gateway(s)
      ansible.builtin.include_tasks: aws-vpc-igw.yaml
      tags: vpc

    - name: Delete Carrier Gateway(s)
      ansible.builtin.include_tasks: aws-vpc-cagw.yaml
      tags: vpc

    - name: AWS | VPC delete
      amazon.aws.ec2_vpc_net:
        state: absent
        region: "{{ vpc_region }}"
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
      register: ret_vpc
      tags: vpc

    - name: AWS | VPC | Show delete result
      ansible.builtin.debug:
        var: ret_vpc
      tags: vpc
