---
- name: Destroy | DNS | AWS | Records
  debug:
    msg: "Destroy DNS Records for zone: {{ zone.name }}"
  tags: dns

- name: Destroy | DNS | AWS | Records delete triggere
  include: aws-dns-record.yaml
  with_items:
    - "api.{{ cluster_state.dns.cluster_domain }}"
    - "api-int.{{ cluster_state.dns.cluster_domain }}"
    - "*.apps.{{ cluster_state.dns.cluster_domain }}"
  loop_control:
    loop_var: record
  tags: dns
