---
- name: Destroy | AWS | VPC Route Tables
  ansible.builtin.debug:
    msg: "Destroy VPC RTB triggered"
  tags: vpc

- name: Destroy | AWS | VPC Rtb - qeury existing
  amazon.aws.ec2_vpc_route_table_info:
    region: "{{ vpc_region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
  register: route_table_info
  tags: vpc

- name: Destroy | AWS | VPC Rtb - set tables to delete
  ansible.builtin.set_fact:
    route_tables_to_delete: "{{ (route_tables_to_delete | default([])) + [item.id] }}"
  when: item.associations | length == 0 or not item.associations[0].main
  loop: "{{ route_table_info.route_tables }}"
  tags: vpc
  no_log: True

- name: Destroy | AWS | VPC Rtb - purge routes
  amazon.aws.ec2_vpc_route_table:
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_id }}"
    route_table_id: "{{ item }}"
    lookup: "id"
    purge_routes: "yes"
    purge_subnets: "yes"
    state: "present"
  loop: "{{ route_tables_to_delete }}"
  when: route_tables_to_delete is defined
  tags: vpc

- name: Destroy | AWS | VPC Rtb - Waiting 10s to propagate
  ansible.builtin.pause:
    seconds: 10
  tags: vpc

- name: Destroy | AWS | VPC Rtb - delete route table
  amazon.aws.ec2_vpc_route_table:
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_id }}"
    route_table_id: "{{ item }}"
    lookup: "id"
    state: "absent"
  loop: "{{ route_tables_to_delete }}"
  when: route_tables_to_delete is defined
  tags: vpc
