---
- name: Destroy | AWS | VPC Internet Gateway
  ansible.builtin.debug:
    msg: "Destroy VPC IGW triggered"
  tags: vpc

- name: Destroy | AWS | VPC IGW - delete internet gateway
  amazon.aws.ec2_vpc_igw:
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_id }}"
    state: "absent"
  with_items: "{{ vpc_info.vpcs }}"
  tags: vpc
  no_log: True
