---
- name: Destroy | AWS | VPC Endpoints
  ansible.builtin.debug:
    msg: "Destroy VPC Endpoint service triggered"
  tags: vpc

- name: Destroy | AWS | VPCe - get all with filters
  amazon.aws.ec2_vpc_endpoint_info:
    region: "{{ vpc_region }}"
    filters:
      vpc-id:
        - "{{ vpc_id }}"
      vpc-endpoint-state:
        - available
        - pending
  register: res_vpce

- name: Destroy | AWS | VPCe - delete endpoints
  amazon.aws.ec2_vpc_endpoint:
    state: absent
    vpc_endpoint_id: "{{ item.vpc_endpoint_id }}"
    region: "{{ vpc_region }}"
  with_items: "{{ res_vpce.vpc_endpoints }}"
  no_log: True
