---
- name: Destroy | VPC | AWS
  ansible.builtin.debug:
    msg: "Destroy VPC subnets triggered"
  tags: vpc
  when: debug|d(false)

- name: Get subnets in the VPC
  ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ vpc_id }}"
  register: ret_subnets
  tags: vpc

- name: Destroy | VPC | Subnets | Show results
  ansible.builtin.debug:
    var: ret_subnets
  tags: vpc
  when: debug|d(false)

- name: Destroy | AWS | Delete subnets
  ec2_vpc_subnet:
    state: absent
    region: "{{ vpc_region }}"
    vpc_id: "{{ item.vpc_id }}"
    cidr: "{{ item.cidr_block }}"
    wait: true
  with_items: "{{ ret_subnets.subnets }}"
  tags: vpc
