---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # This should be set via the command line at runtime.
    tag: ''
    build_dir: "{{ playbook_dir }}/../../build"

  pre_tasks:
    - name: Verify none of the git submodules need updates.
      command: >
        git submodule update --recursive --remote
        chdir=../
      register: git_update
      failed_when: git_update.stdout != ''
      tags: build

    - name: Ensure the ~/.ansible directory exists.
      file:
        path: "{{ build_dir }}"
        state: directory
      tags: build

    - name: Ensure the ANSIBLE_GALAXY_TOKEN environment variable is set.
      fail:
        msg: ANSIBLE_GALAXY_TOKEN is not set.
      when: "lookup('env','ANSIBLE_GALAXY_TOKEN') == ''"
      no_log: true
      tags: deploy

    - name: Ensure the ~/.ansible directory exists.
      file:
        path: ~/.ansible
        state: directory
      tags: deploy

    - name: Write the Galaxy token to ~/.ansible/galaxy_token
      copy:
        content: |
          token: {{ lookup('env','ANSIBLE_GALAXY_TOKEN') }}
        dest: ~/.ansible/galaxy_token
      no_log: true
      tags: deploy

  tasks:
    - name: Template out the galaxy.yml file.
      template:
        src: templates/galaxy.yml.j2
        dest: ../../galaxy.yml
      tags: build

    - name: Build the collection.
      command: >
        ansible-galaxy collection build \
          --output-path {{ build_dir }}
        chdir=../
      tags: build

    - name: Publish the collection.
      command: >
        ansible-galaxy collection publish \
          {{ build_dir }}/mtulio-okd_installer-{{ tag }}.tar.gz
        chdir=../
      tags: deploy
