---

- name: Check | Assert required variables - cluster_name
  ansible.builtin.assert:
    that:
      - cluster_name is defined
      - config_metadata_name is defined
    fail_msg: "'cluster_name' is not defined"
