---

- name: Create | Assertions | Variables
  ansible.builtin.include_tasks: check-vars.yaml

- name: Create | Assertions | Check required provider
  ansible.builtin.assert:
    that:
      - provider is in config_valid_providers
    fail_msg: "'provider' is not a valid provider {{ config_valid_providers }}"

- name: Create | Assrt. | Directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    recurse: yes
  with_items:
    - "{{ config_install_dir }}"

- name: Create | Assrt. | Set bin path
  ansible.builtin.stat:
    path: "{{ bin_openshift_install }}"
  register: bin_oi_out

- name: Create | Assrt. | Installer path
  ansible.builtin.debug:
    msg: "openshift-install binary not found on path: '{{ bin_openshift_install }}'"
  failed_when: not(bin_oi_out.stat.exists)

- name: Create | Assrt. | CONFIG_PULL_SECRET_FILE
  ansible.builtin.stat:
    path: "{{ config_pull_secret_file }}"
  register: ps_out

- name: Create | Assrt. | pull secret file
  ansible.builtin.debug:
    msg: "CONFIG_PULL_SECRET_FILE env var was not found. Please set it with pull-secret file path"
  failed_when: not(ps_out.stat.exists)

# Creaete state files to validate each configuration state.

- name: Create | Config | Check file manifests/cluster-config.yaml
  ansible.builtin.stat:
    path: "{{ config_install_dir }}/install-config.yaml"
  register: _installconfig

- name: Create | Assrt. | Check file manifests/cluster-config.yaml
  ansible.builtin.stat:
    path: "{{ config_install_dir }}/manifests/cluster-config.yaml"
  register: _manifests

- name: Create | Assrt. | Check file metadata.json
  ansible.builtin.stat:
    path: "{{ config_install_dir }}/metadata.json"
  register: _metadata

- name: Create | Assrt. | Check file coreos-stream.json
  ansible.builtin.stat:
    path: "{{ config_install_dir }}/coreos-stream.json"
  register: _coreosstream

- name: Create | Assrt. | Check file bootstrap.ign
  ansible.builtin.stat:
    path: "{{ config_install_dir }}/bootstrap.ign"
  register: _ign_bootstrap

- name: Create | Assrt. | Check file .bootstrap.ign.stat
  ansible.builtin.stat:
    path: "{{ config_install_dir }}/.bootstrap.ign.stat"
  register: _ign_bootstrap_stat