--- # create-config manages the install-config.yaml

- name: Create | Config | Run Check vars
  ansible.builtin.include_tasks: check.yaml

- name: Create | Config | Run custom assertions
  ansible.builtin.include_tasks: create-assertions.yaml

- name: Create | Config | Render Install config file
  when:
    - not(_installconfig.stat.exists)
    - not(_manifests.stat.exists)
    - not(_metadata.stat.exists)
  block:
  - name: Create | Config | Render Install config file
    ansible.builtin.template:
      src: install-config.yaml.j2
      dest: "{{ config_install_dir }}/install-config.yaml"
      mode: 0644

  - name: Create | Config | Copy/Save the rendered install config
    ansible.builtin.copy:
      src: "{{ config_install_dir }}/install-config.yaml"
      dest: "{{ config_install_dir }}/install-config-bkp.yaml"
      mode: 0644

  - name: Create | Config | Show
    ansible.builtin.debug:
      msg: "Installer configuration generated at path: {{ config_install_dir }}/install-config.yaml"

- name: Create | Manifests | CoreOS Stream JSON
  ansible.builtin.include_tasks: create-coreos-stream.yml
