---
# tasks to patch ignition files, mostly bootstrap.ign.
# requires filetranspiler:
# https://raw.githubusercontent.com/ashcrow/filetranspiler/1.1.3/filetranspile

- name: install filetranspile dependencies
  pip:
    state: latest
    name: 
    - pip
    - pyyaml
    - python-magic

# - stat:

- name: Patch | Ignitions | Run Load vars
  ansible.builtin.include_tasks: load.yaml

- name: Patch | Ignitions | Run custom assertions
  ansible.builtin.include_tasks: create-assertions.yaml

- name: Patch | Ignitions | Generate
  when:
    - _ign_bootstrap.stat.exists
    - not(_ign_bootstrap_stat.stat.exists)
  block:
  - name: Patch | Apply patches on Ignitions stage
    ansible.builtin.include_tasks:
      file: "patches-ignitions/{{ patch_name }}.yaml"
    loop_control:
      loop_var: patch_name
    loop: "{{ config_patches_ignitions | d([]) }}"

  - file:
      state: touch
      path: "{{ config_install_dir }}/.bootstrap.ign.stat"