---

- name: Save cluster_state to cluster_state.json
  ansible.builtin.copy:
    dest: "{{ config_install_dir + '/cluster_state.json' }}"
    content: "{{ cluster_state }}"
    mode: 0644
  changed_when: false
