---
okd_cluster_destroy_instances:
  - name: "{{ cluster_state.infra_id }}-bootstrap"
  - name: "{{ cluster_state.infra_id }}-master-1"
  - name: "{{ cluster_state.infra_id }}-master-2"
  - name: "{{ cluster_state.infra_id }}-master-3"
  - name: "{{ cluster_state.infra_id }}-worker-1"
  - name: "{{ cluster_state.infra_id }}-worker-2"
  - name: "{{ cluster_state.infra_id }}-worker-3"
  - name: "{{ cluster_state.infra_id }}-worker-4"
    wait: yes
    wait_timeout: 120

okd_cluster_destroy_dns_records:
  - "api.{{ cluster_state.dns.cluster_domain }}"
  - "api-int.{{ cluster_state.dns.cluster_domain }}"
  - "*.apps.{{ cluster_state.dns.cluster_domain }}"
