---
- name: Patch | OCI | CCM | Set namespace oci_ccm_namespace
  ansible.builtin.set_fact:
    # default provided by repo is kube-system
    oci_csi_namespace: oci-csi
  when: oci_csi_namespace is not defined

- name: Patch | OCI | CSI | Load OCI Secret data
  ansible.builtin.set_fact:
    oci_ccm_secret_data: "{{ lookup('template', 'patches/oci/oci-ccm-01-secret-data.yaml.j2') | from_yaml }}"

- name: Patch | OCI | CSI | Create Manifests to install dir manifests/
  ansible.builtin.template:
    src: "patches/oci/{{ manifest }}.j2"
    dest: "{{ config_install_dir }}/manifests/{{ manifest }}"
    mode: 0644
  loop_control:
    loop_var: manifest
  loop:
  - oci-csi-00-namespace.yaml
  - oci-csi-01-secret.yaml
  - oci-csi-02-node-rbac-00-sa.yaml
  - oci-csi-02-node-rbac-01-cr.yaml
  - oci-csi-02-node-rbac-02-crb.yaml
  - oci-csi-03-controller-driver.yaml
  - oci-csi-04-node-driver-00-csidriver-fss.yaml
  - oci-csi-04-node-driver-01-csidriver-bv.yaml
  - oci-csi-04-node-driver-02-cm-iscsi.yaml
  - oci-csi-04-node-driver-03-cm-fss.yaml
  - oci-csi-04-node-driver-04-daemonset.yaml
  - oci-csi-05-storage-class-00-bv.yaml
  - oci-csi-05-storage-class-01-bv-enc.yaml

- name: Patch | OCI | CSI | Create MachineConfig iscsid.service
  ansible.builtin.template:
    src: patches/mc-iscsid-service.yaml.j2
    dest: "{{ config_install_dir }}/openshift//99_openshift-machineconfig_99-{{ machine_role }}-iscsid.yaml"
  loop_control:
    loop_var: machine_role
  loop:
  - master
  - worker