---
- name: Create | Render Install config file
  ansible.builtin.template:
    src: patches/mc-disk-var-lib-containers.yaml.j2
    dest: "{{ config_install_dir }}/openshift/98-var-lib-containers-{{ machineconfiguration_role }}.yaml"
    mode: 0644
  loop: "{{ cfg_patch_mc_varlibcontainers.machineconfiguration_roles }}"
  loop_control:
    loop_var: machineconfiguration_role
