---
- name: Create | Remove Cluster/Machine API manifests for UPI
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_master-machines-1.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_master-machines-2.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_master-machines-3.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-1.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-2.yaml"
    - "{{ config_install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-3.yaml"
