---
- name: Dump state to file
  hosts: localhost
  connection: local

  tasks:
    - name: Show Current Config
      ansible.builtin.debug:
        var: cluster_state

    - name: Save cluster state locally
      ansible.builtin.copy:
        dest: "{{ install_dir }}/cluster_state.json"
        content: "{{ cluster_state }}"
        mode: 0640
