---
- name: OpenShift Install Config Generator
  hosts: localhost
  connection: local

  vars_prompt:
    - name: install_dir
      prompt: What is the Installation Directory?
      private: false
    - name: name
      prompt: What is the cluster name?
      private: false

  vars_files:
    - vars/openshift.yaml

  roles:
    - okd_installer_config
