---
- name: OKD Stack Compute - Start
  hosts: '{{ target|default("localhost") }}'
  connection: local

  tasks:
    - name: Show date time
      ansible.builtin.set_fact:
        datetime_start: "{{ ansible_date_time.iso8601 }}"


- ansible.builtin.import_playbook: var_check_required.yaml

- ansible.builtin.import_playbook: config.yaml
  vars:
    mode: create

- ansible.builtin.import_playbook: stack_network.yaml

- ansible.builtin.import_playbook: stack_iam.yaml

- ansible.builtin.import_playbook: stack_dns.yaml

- ansible.builtin.import_playbook: stack_loadbalancer.yaml

- ansible.builtin.import_playbook: create_node_all.yaml

- ansible.builtin.import_playbook: stack_loadbalancer.yaml
  vars:
    var_file: "{{ playbook_dir }}/vars/{{ config_provider }}/loadbalancer-router-default.yaml"
  when:
    - (config_provider is defined)
    - (config_platform|d('') != "aws")

- ansible.builtin.import_playbook: approve_certs.yaml
  vars:
    certs_max_retries: 5
    cert_wait_interval_sec: 60
  when: 
    - (config_provider == 'aws') or (config_platform == 'none')

- ansible.builtin.import_playbook: create_imageregistry.yaml
  when: 
    - (config_provider == 'aws') or (config_platform == 'none')
    - create_registry|d('no') == 'yes'


- name: OKD Stack Compute - Finish
  hosts: '{{ target|default("localhost") }}'
  connection: local

  tasks:
    - name: Show date time
      ansible.builtin.debug:
        msg: "start=[{{ datetime_start|d('') }}] end=[{{ ansible_date_time.iso8601 }}]"
