---
- name: okd-installer | Create Stack | Compute | Load Config
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: okd-installer | Create Stack | Compute
  hosts: '{{ target|default("localhost") }}'
  connection: local
  vars:
    profile_path: "{{ playbook_dir }}/vars/{{ config_provider }}/profiles/{{ cluster_profile|d('default') }}"

  vars_prompt:
    - name: node_role
      prompt: What is the Compute Node Role to be created [bootstrap,controlplace,compute]?
      private: false

  pre_tasks:
    - name: Show node_role
      ansible.builtin.debug:
        msg: "node_role: {{ node_role }}"

    - name: Include User Provided Compute Variables
      ansible.builtin.include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: okd-installer | Stack | Compute | Include Vars - Pre-build topologies
      ansible.builtin.include_vars:
        file: "{{ profile_path }}/node-{{ node_role }}.yaml"
      when: var_file is not defined

  roles:
    - role: bootstrap
      when: (node_role | d('') == 'bootstrap') or (cluster_profile | d('') == 'sno')
    - role: cloud_compute


- name: okd-installer | Create Stack | Compute | Save state
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: save-state
    cluster_state: "{{ cluster_state | combine({'compute': cloud_compute_state}) }}"
