---
- import_playbook: var_check_required.yaml

- import_playbook: config.yaml
  vars:
    mode: load

- name: OKD Destroy Cluster
  hosts: '{{target|default("localhost")}}'
  connection: local

  vars_files:
    - "./vars/{{ provider }}/iam.yaml"
    - "./vars/{{ provider }}/dns.yaml"
    - "./vars/{{ provider }}/network.yaml"

  pre_tasks:
    - name: Destroy | Preparing the list of Load Balancers
      ansible.builtin.set_fact:
        load_balancers_all: []

    - name: Destroy | Loading Router Default Load Balancers
      include_vars:
        file: "./vars/{{ provider }}/loadbalancer-router-default.yaml"

    - name: Destroy | Saving Default Router to the List
      ansible.builtin.set_fact:
        load_balancers_all: "{{ load_balancers_all + cloud_loadbalancers }}"

    - name: Destroy | Loading ControlPlane Load Balancers
      include_vars:
        file: "./vars/{{ provider }}/loadbalancer.yaml"

    - name: Destroy | Saving Default Router to the List
      ansible.builtin.set_fact:
        load_balancers_all: "{{ load_balancers_all + cloud_loadbalancers }}"

    - name: Destroy | Saving the final list of Load Balancers
      ansible.builtin.set_fact:
        cloud_loadbalancers: "{{ load_balancers_all }}"

    - name: Destroy | Saving the final list of Load Balancers
      ansible.builtin.debug:
        msg: "Found {{ cloud_loadbalancers |length }} Load Balancers on the Configuration"

  roles:
    - role: okd_cluster_destroy
