---
- import_playbook: config_load.yaml
  tags: always

- name: OpenShift Destroy Cluster
  hosts: localhost
  connection: local

  vars_prompt:
    - name: install_dir
      prompt: What is the Installation Directory?
      private: false
    - name: provider
      prompt: What is the Provider the cluster was installed?
      private: false

  vars_files:
    - "vars/openshift.yaml"
    - "vars/loadbalancers/ocp-{{ config |d(ocp_config_provider) | d(provider) }}.yaml"
    - "vars/iam/ocp-{{ ocp_config_provider | d(provider) }}.yaml"
    - "vars/dns/ocp-{{ ocp_config_provider | d(provider) }}.yaml"
    - "vars/networks/ocp-{{ ocp_config_provider | d(provider) }}-{{ ocp_config_region | d(region) }}.yaml"

  roles:
    - role: okd_cluster_destroy
