---
- name: okd-installer | Cluster Destroy | Start
  hosts: '{{ target|default("localhost") }}'
  connection: local
  gather_facts: yes
  tasks:
    - name: OKD Installer | Destroy | Timer start
      ansible.builtin.set_fact:
        okdi_del_timer_start: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- name: okd-installer | Cluster Destroy | Config load
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: okd-installer | Cluster Destroy
  hosts: '{{target|default("localhost")}}'
  connection: local
  gather_facts: yes

  vars:
    profile_path: "{{ playbook_dir }}/vars/{{ config_provider }}/profiles/{{ cluster_profile|d('default') }}"

  vars_files:
    - "{{ profile_path }}/iam.yaml"
    - "{{ profile_path }}/dns.yaml"

  pre_tasks:
    # Network
    - name: okd-installer | Destroy | Network | Loading Topology Names
      ansible.builtin.include_vars:
        file: "{{ profile_path }}/network.yaml"

    # Load Balancers
    - name: okd-installer | Destroy | LB | Init list
      ansible.builtin.set_fact:
        load_balancers_all: []

    - name: okd-installer | Destroy | Load Resource Names
      ansible.builtin.include_vars:
        file: "{{ profile_path }}/destroy_resources.yaml"

    - name: okd-installer | Destroy | LB | Load Router Names
      ansible.builtin.include_vars:
        file: "{{ profile_path }}/loadbalancer-router-default.yaml"

    - name: okd-installer | Destroy | LB | Merge
      ansible.builtin.set_fact:
        load_balancers_all: "{{ (load_balancers_all | d([])) + (cloud_loadbalancers | d([])) }}"

    - name: okd-installer | Destroy | LB | Load API Names
      ansible.builtin.include_vars:
        file: "{{ profile_path }}/loadbalancer.yaml"

    - name: okd-installer | Destroy | LB | Merge
      ansible.builtin.set_fact:
        load_balancers_all: "{{ load_balancers_all + (cloud_loadbalancers | d([])) }}"

    - name: okd-installer | Destroy | LB | Consolidate
      ansible.builtin.set_fact:
        cloud_loadbalancers: "{{ load_balancers_all }}"

    - name: okd-installer | Destroy | LB | Show resource count
      ansible.builtin.debug:
        msg: "Found {{ cloud_loadbalancers | length }} Load Balancers on the Configuration"

  roles:
    - role: destroy

  post_tasks:
    - name: okd-installer | Destroy | Finish | Timer end
      ansible.builtin.set_fact:
        okdi_del_timer_end: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: okd-installer | Destroy | Finish | Show timers
      ansible.builtin.debug:
        msg:
        - "start=[{{ okdi_del_timer_start | d('') }}] end=[{{ okdi_del_timer_end }}]"
        - "total=[{{ ((okdi_del_timer_end | to_datetime) - (okdi_del_timer_start | to_datetime)) }}]"