---
- name: okd-installer | Cluster Destroy | Start
  hosts: '{{ target|default("localhost") }}'
  connection: local
  gather_facts: yes

  tasks:
    - name: OKD Installer | Destroy | Timer start
      ansible.builtin.set_fact:
        okdi_del_timer_start: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

# - ansible.builtin.import_playbook: var_check_required.yaml

- name: okd-installer | Cluster Destroy | Config load
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: okd-installer | Cluster Destroy
  hosts: '{{target|default("localhost")}}'
  connection: local
  gather_facts: yes
  vars_files:
    - "./vars/{{ config_provider }}/iam.yaml"
    - "./vars/{{ config_provider }}/dns.yaml"
  pre_tasks:
    # Network
    - name: okd-installer | Destroy | Network | Loading Topology Names
      ansible.builtin.include_vars:
        file: "./vars/{{ config_provider }}/topologies/{{ topology_network }}/network.yaml"
      when: topology_network is defined

    - name: okd-installer | Destroy | Network | Loading Default Names
      ansible.builtin.include_vars:
        file: "./vars/{{ config_provider }}/network.yaml"
      when: topology_network is not defined

    # Load Balancers
    - name: okd-installer | Destroy | LB | Init list
      ansible.builtin.set_fact:
        load_balancers_all: []

    - name: okd-installer | Destroy | Load Resource Names
      ansible.builtin.include_vars:
        file: "./vars/{{ config_provider }}/destroy_resources.yaml"

    - name: okd-installer | Destroy | LB | Load Router Names
      ansible.builtin.include_vars:
        file: "./vars/{{ config_provider }}/loadbalancer-router-default.yaml"

    - name: okd-installer | Destroy | LB | Merge list
      ansible.builtin.set_fact:
        load_balancers_all: "{{ load_balancers_all + cloud_loadbalancers }}"

    - name: okd-installer | Destroy | LB | Load API Names
      ansible.builtin.include_vars:
        file: "./vars/{{ config_provider }}/loadbalancer.yaml"

    - name: okd-installer | Destroy | LB | Merge list
      ansible.builtin.set_fact:
        load_balancers_all: "{{ load_balancers_all + cloud_loadbalancers }}"

    - name: okd-installer | Destroy | LB | Consolidate
      ansible.builtin.set_fact:
        cloud_loadbalancers: "{{ load_balancers_all }}"

    - name: okd-installer | Destroy | LB | Show number of resources
      ansible.builtin.debug:
        msg: "Found {{ cloud_loadbalancers | length }} Load Balancers on the Configuration"

  roles:
    - role: destroy


- name: okd-installer | Destroy | Finish
  hosts: '{{ target|default("localhost") }}'
  connection: local
  gather_facts: true
  tasks:
    - name: okd-installer | Destroy | Finish | Timer end
      ansible.builtin.set_fact:
        okdi_del_timer_end: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: okd-installer | Destroy | Finish | Show timers
      ansible.builtin.debug:
        msg:
        - "start=[{{ okdi_del_timer_start | d('') }}] end=[{{ okdi_del_timer_end }}]"
        - "total=[{{ ((okdi_del_timer_end | to_datetime) - (okdi_del_timer_start | to_datetime)) }}]"
