---
# - ansible.builtin.import_playbook: var_check_required.yaml

- name: okd-installer | Stack | Load Balancer | Config load
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: okd-installer | Stack | Load Balancer
  hosts: '{{target|default("localhost")}}'
  connection: local
  vars:
    cloud_loadbalancers_state: []
    profile_path: "{{ playbook_dir }}/vars/{{ config_provider }}/profiles/{{ cluster_profile|d('default') }}"

  tasks:
    - name: okd-installer | Stack | LB | Include vars - User Provided
      ansible.builtin.include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: okd-installer | Stack | LB | Include Vars - Profiles
      ansible.builtin.include_vars:
        file: "{{ profile_path }}/loadbalancer.yaml"
      when: var_file is not defined

    - name: okd-installer | Stack | LB | setup
      ansible.builtin.include_role:
        name: cloud_load_balancer

    - name: okd-installer | Stack | LB | update cluster_state
      ansible.builtin.set_fact:
        cluster_state: "{{ cluster_state | combine({'loadbalancers': cloud_loadbalancers_state}) }}"

    - name: okd-installer | Stack | LB | save cluster_state
      ansible.builtin.include_role:
        name: config
      vars:
        mode: save-state
