---
# - ansible.builtin.import_playbook: var_check_required.yaml

- name: okd-installer | Stack | Load Balancer | Config load
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: okd-installer | Stack | Load Balancer
  hosts: '{{target|default("localhost")}}'
  connection: local

  pre_tasks:
    - name: okd-installer | Stack | LB | Include vars - User Provided
      ansible.builtin.include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: okd-installer | Stack | LB | Include vars - default
      ansible.builtin.include_vars:
        file: "./vars/{{ provider }}/loadbalancer.yaml"
      when:
        - (cloud_loadbalancers is not defined) or (cloud_loadbalancers | length <= 0)

  roles:
    - cloud_load_balancer

- name: okd-installer | Stack | LB | Save state
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: save-state
    cluster_state: "{{ cluster_state | combine({'load_balancers': cloud_load_balancers_state}) }}"
