---
# - ansible.builtin.import_playbook: var_check_required.yaml

- name: okd-installer | Stack | IAM | Config load
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: okd-installer | Stack | IAM
  hosts: '{{target|default("localhost")}}'
  connection: local
  vars:
    profile_path: "{{ playbook_dir }}/vars/{{ config_provider }}/profiles/{{ cluster_profile|d('default') }}"

  pre_tasks:
    - name: okd-installer | Stack | IAM | Include vars - user provided
      ansible.builtin.include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: okd-installer | Stack | IAM | Include Vars - Profiles
      ansible.builtin.include_vars:
        file: "{{ profile_path }}/iam.yaml"
      when: var_file is not defined

  roles:
    - cloud_iam

- name: okd-installer | Stack | IAM | Save state
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: save-state
    cluster_state: "{{ cluster_state | combine({'iam': cloud_iam_state}) }}"
