---
# - ansible.builtin.import_playbook: var_check_required.yaml

- name: OKD Stack IAM | Config load
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: OKD Stack IAM
  hosts: '{{target|default("localhost")}}'
  connection: local

  pre_tasks:
    - name: Include User Provided IAM Variables
      ansible.builtin.include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: Include IAM Variables
      ansible.builtin.include_vars:
        file: "./vars/{{ provider }}/iam.yaml"
      when: cloud_iam is not defined

  roles:
    - cloud_iam

- name: OKD Stack IAM | Save state
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: save-state
    cluster_state: "{{ cluster_state | combine({'iam': cloud_iam_state}) }}"
