---
- import_playbook: var_check_required.yaml

- import_playbook: config.yaml
  vars:
    mode: load

- name: OKD Stack DNS
  hosts: '{{target|default("localhost")}}'
  connection: local

  pre_tasks:
    - name: Include User Provided DNS Variables
      include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: Include DNS Variables
      include_vars:
        file: "./vars/{{ provider }}/dns.yaml"
      when: cloud_networks is not defined

  roles:
    - cloud_dns

- import_playbook: config.yaml
  vars:
    mode: save-state
    cluster_state: "{{ cluster_state | combine({'dns': cloud_dns_state}) }}"
