---
# - ansible.builtin.import_playbook: var_check_required.yaml

- name: okd-installer | Stack | DNS | Config load
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: okd-installer | Stack | DNS
  hosts: '{{ target | default("localhost") }}'
  connection: local

  pre_tasks:
    - name: okd-installer | Stack | DNS | Include Vars - User provided
      ansible.builtin.include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: okd-installer | Stack | DNS | Include Vars - Pre-build topologies
      ansible.builtin.include_vars:
        file: "./vars/{{ provider }}/topologies/{{ topology_dns }}/dns.yaml"
      when: topology_dns is defined

    - name: okd-installer | Stack | DNS | Include Vars - default
      ansible.builtin.include_vars:
        file: "./vars/{{ provider }}/dns.yaml"
      when:
        - (cloud_dns_zones is not defined) or (cloud_dns_zones | length <= 0)

  roles:
    - cloud_dns

- name: okd-installer | Stack | DNS | Save state
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: save-state
    cluster_state: "{{ cluster_state | combine({'dns': cloud_dns_state}) }}"
