---
- import_playbook: config_load.yaml

- hosts: localhost
  
  # To skip prompt, define the extra-arg 'name'
  vars_prompt:
    - name: provider
      prompt: What is the cloud provider name?
      private: false
    - name: name
      prompt: What is the network name?
      private: false

  pre_tasks:
    - name: Include network vars
      include_vars: "vars/networks/{{ name }}-{{ provider }}-{{ region }}.yaml"

  roles:
    - role: cloud_network


- import_playbook: config_dump.yaml
