---
# - ansible.builtin.import_playbook: var_check_required.yaml

- name: okd-installer | Stack | DNS | Config load
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: load

- name: okd-installer | Stack | DNS
  hosts: '{{ target | default("localhost") }}'
  connection: local
  vars:
    profile_path: "{{ playbook_dir }}/vars/{{ config_provider }}/profiles/{{ cluster_profile|d('default') }}"

  pre_tasks:
    - name: okd-installer | Stack | DNS | Include Vars - User provided
      ansible.builtin.include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: okd-installer | Stack | DNS | Include Vars - Profiles
      ansible.builtin.include_vars:
        file: "{{ profile_path }}/dns.yaml"
      when: var_file is not defined

  roles:
    - cloud_dns

- name: okd-installer | Stack | DNS | Save state
  ansible.builtin.import_playbook: config.yaml
  vars:
    mode: save-state
    cluster_state: "{{ cluster_state | combine({'dns': cloud_dns_state}) }}"
