---
- import_playbook: var_check_required.yaml

- import_playbook: config.yaml
  vars:
    mode: load

- name: OKD Stack Network
  hosts: '{{target|default("localhost")}}'
  connection: local

  tasks:
    - name: Include Network Variables
      include_vars:
        file: "./vars/{{ provider }}/network.yaml"
      when: cloud_networks is not defined

  roles:
    - cloud_network

- import_playbook: config.yaml
  vars:
    mode: save-state

#- import_playbook: config_dump.yaml
