---
- import_playbook: var_check_required.yaml

- import_playbook: config.yaml
  vars:
    mode: load

- name: OKD Stack Load Balancer
  hosts: '{{target|default("localhost")}}'
  connection: local

  pre_tasks:
    - name: Include User Provided Load Balancer Variables
      include_vars:
        file: "{{ var_file }}"
      when: var_file is defined

    - name: Include Locad Balancer Variables
      include_vars:
        file: "./vars/{{ provider }}/loadbalancer.yaml"
      when: cloud_loadbalancers is not defined

  roles:
    - cloud_load_balancer

- import_playbook: config.yaml
  vars:
    mode: save-state
    cluster_state: "{{ cluster_state | combine({'load_balancers': cloud_load_balancers_state}) }}"
