---

cloud_load_balancer_provider: oci

# BackendSet
# https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/4.12.0/collections/oracle/oci/oci_network_load_balancer_backend_set_module.html#ansible-collections-oracle-oci-oci-network-load-balancer-backend-set-module
# cloud_loadbalancer_targets:
#   - name: "{{ cluster_state.infra_id }}-aext"
#     provider: oci
#     spec:
#       name: "{{ cluster_state.infra_id }}-aext"
#       compartment_id: "{{ oci_compartment_id }}"
#       is_preserve_source: no
#       ip_version: IPV4
#       #policy: TWO_TUPLE
#       #backends: []
#       health_checker:
#         port: 6443
#         protocol: HTTPS
#         return_code: 200
#         url_path: /readyz
#         interval_in_millis: 10000
#         timeout_in_millis: 3000


# OCI NLB: https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/4.12.0/collections/oracle/oci/oci_network_load_balancer_module.html#ansible-collections-oracle-oci-oci-network-load-balancer-module
cloud_loadbalancers:
  - name: "{{ cluster_state.infra_id }}-nlb"
    provider: oci
    type: network

    # Is it supported multi-subnets?
    subnet_name: "{{ cluster_state.infra_id }}-net-public"
    nsg_name: "{{ cluster_state.infra_id }}-nsg-nlb"
    spec:
      compartment_id: "{{ oci_compartment_id }}"
      display_name: "{{ cluster_state.infra_id }}-nlb"
      is_private: false
      is_preserve_source_destination: false
      nlb_ip_version: IPV4
      #freeform_tags: "{{ cluster_state.tags }}"

# BackendSet
# https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/4.12.0/collections/oracle/oci/oci_network_load_balancer_backend_set_module.html#ansible-collections-oracle-oci-oci-network-load-balancer-backend-set-module
    backend_set:
    - provider: oci
      spec:
        name: "{{ cluster_state.infra_id }}-api"
        is_preserve_source: false
        ip_version: IPV4
        policy: FIVE_TUPLE
        #backends: []
        health_checker:
          port: 6443
          protocol: HTTPS
          return_code: 200
          url_path: /readyz
          interval_in_millis: 10000
          timeout_in_millis: 3000

    - provider: oci
      spec:
        name: "{{ cluster_state.infra_id }}-mcs"
        is_preserve_source: false
        ip_version: IPV4
        policy: FIVE_TUPLE
        #backends: []
        health_checker:
          port: 22623
          protocol: HTTPS
          return_code: 200
          url_path: /healthz
          interval_in_millis: 10000
          timeout_in_millis: 3000

    - provider: oci
      spec:
        name: "{{ cluster_state.infra_id }}-ingress-http"
        is_preserve_source: false
        ip_version: IPV4
        policy: FIVE_TUPLE
        #backends: [] # TCP/31794
        health_checker:
          port: 80
          protocol: TCP
          # return_code: 200
          # url_path: /healthz
          interval_in_millis: 10000
          timeout_in_millis: 3000

    - provider: oci
      spec:
        name: "{{ cluster_state.infra_id }}-ingress-https"
        is_preserve_source: false
        ip_version: IPV4
        #policy: TWO_TUPLE
        #backends: [] # TCP/32186
        health_checker:
          port: 443
          protocol: TCP
          # return_code: 200
          # url_path: /healthz
          interval_in_millis: 10000
          timeout_in_millis: 3000

    # https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/4.12.0/collections/oracle/oci/oci_network_load_balancer_listener_module.html#ansible-collections-oracle-oci-oci-network-load-balancer-listener-module
    listeners:
      - spec:
          name: "{{ cluster_state.infra_id }}-api"
          default_backend_set_name: "{{ cluster_state.infra_id }}-api"
          ip_version: IPV4
          port: 6443
          protocol: TCP

      - spec:
          name: "{{ cluster_state.infra_id }}-mcs"
          default_backend_set_name: "{{ cluster_state.infra_id }}-mcs"
          ip_version: IPV4
          port: 22623
          protocol: TCP

      - spec:
          name: "{{ cluster_state.infra_id }}-ingress-http"
          default_backend_set_name: "{{ cluster_state.infra_id }}-ingress-http"
          ip_version: IPV4
          port: 80
          protocol: TCP

      - spec:
          name: "{{ cluster_state.infra_id }}-ingress-https"
          default_backend_set_name: "{{ cluster_state.infra_id }}-ingress-https"
          ip_version: IPV4
          port: 443
          protocol: TCP

    callbacks:
      - name: register_dns
        rr_ip: public
        spec:
          zone_name_or_id: "{{ cluster_state.dns.base_domain }}"
          compartment_id: "{{ oci_compartment_id_dns | d(oci_compartment_id) }}"
          scope: GLOBAL
          patch_items:
            - domain: "api.{{ cluster_state.dns.cluster_domain }}"
              rtype: A
              ttl: 300
            - domain: "*.apps.{{ cluster_state.dns.cluster_domain }}"
              rtype: A
              ttl: 300
      - name: register_dns
        rr_ip: private
        spec:
          zone_name_or_id: "{{ cluster_state.dns.base_domain }}"
          compartment_id: "{{ oci_compartment_id_dns | d(oci_compartment_id) }}"
          scope: GLOBAL
          patch_items:
            - domain: "api-int.{{ cluster_state.dns.cluster_domain }}"
              rtype: A
              ttl: 300
      
      # # private address
      # - name: register_dns
      #   rr_ip: private
      #   view_name: "{{ cluster_state.infra_id }}-vcn"
      #   spec:
      #     zone_name_or_id: "{{ cluster_state.dns.cluster_domain }}"
      #     compartment_id: "{{ oci_compartment_id }}"
      #     scope: PRIVATE
      #     patch_items:
      #       - domain: "api-int.{{ cluster_state.dns.cluster_domain }}"
      #         rtype: A
      #         ttl: 300
      
      # - name: register_dns
      #   rr_ip: public
      #   view_name: "{{ cluster_state.infra_id }}-vcn"
      #   spec:
      #     zone_name_or_id: "{{ cluster_state.dns.cluster_domain }}"
      #     compartment_id: "{{ oci_compartment_id }}"
      #     scope: PRIVATE
      #     patch_items:
      #       - domain: "api.{{ cluster_state.dns.cluster_domain }}"
      #         rtype: A
      #         ttl: 300
      #       - domain: "*.apps.{{ cluster_state.dns.cluster_domain }}"
      #         rtype: A
      #         ttl: 300
